### ISSUE TITLE
Bug: Produces invalid query when trying to access same node with different args > twice

### ISSUE THREAD

**Issue by zenflow** [gqless/gqless#100]
I've created a reproduction to help make the bug clear: https://gqless-merged-queries-bug.now.sh/ ([source code](https://github.com/zenflow/gqless-merged-queries-bug/blob/master/pages/index.js))

If you increase "Number of pages" by 1 or 2 it's fine. For example, if you increase the number from 1 to 3, you can see gqless produces a query like this: 

```
{
  allPosts__1:allPosts(first:5,skip:5){title},
  allPosts(first:5,skip:10){title}}
}
```

But if you increase "Number of pages" by more than 2, gqless produces an invalid query which is rejected by the graphql server. For example, if you increase the number from 3 to 6, you can see gqless produces a query like this:

```
{
  allPosts__2:allPosts(first:5,skip:15){title},
  allPosts(first:5,skip:20){title},
  allPosts(first:5,skip:25){title}
}
```

Which gets the obvious error from the graphql server:

`Field 'allPosts' conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional.`

**Comment by samdenty** [comment]
@zenflow As the GraphQL variables are changing (non-static), you should use `useVariable`. By doing this, the Variable will act as a "key" amongst other things.

This is definitely a bug though, can you provide the repo?

Additionally, you can add [`@gqless/logger`](https://www.npmjs.com/package/@gqless/logger) with the verbose option - which will provide more debugging info

**Comment by zenflow** [comment]
> You can add @gqless/logger with the verbose option - which will provide more debugging info

Thanks for the tip! Installed it!

> Additionally, as the GraphQL arguments are changing (non-static), you should use useVariable. By doing this, the Variable object will act as a "key" - rather than the actual value.

So the GraphqQL argument that changes (`skip`), is different from one `PageOfPosts` instance to another, but *is constant with a PageOfPosts instance (across renders)*, so it doesn't seem like an appropriate place to use `useVariable`, but I went for it anyways and had some strange results. See https://github.com/zenflow/gqless-merged-queries-bug/pull/1 and the deployment. It looks like I'm getting the same `Variable` in each PageOfPosts instance, when I was expecting a different `Variable` (with different value) for each PageOfPosts instance. Weird. Why does this happen?

Anyways I think the point of using gqless `Variables` is to use graphql query variables. (Right? Please correct me on that if I'm wrong.) And I don't see the point of graphql query variables, except for being able to factor out some variables and name each query for gql api performance monitoring, which I don't really care about, so I guess there's no point of me using them. I don't think this library should worry about it (being able to name queries) either. Just my two cents.

**Comment by PabloSzx** [comment]
Hi @zenflow, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉

**Comment by zenflow** [comment]
@PabloSzx Was the issue fixed? This seems like a pretty critical bug in the heart of gqless magic, To be honest this is the only issue with gqless that prevents me from adopting it over apollo, since I don't see gqless as reliable. Also I think it will continue to come up until it's fixed (see #128).
I did have a look at the source code to see if I could figure out what is going wrong, but it was a little over my head to start, and would have took more time to understand.
Would it help if I updated the reproduction [repo](http://github.com/zenflow/gqless-merged-queries-bug) & [app](https://gqless-merged-queries-bug.now.sh/)? It looks like the public graphql server it uses was taken down, so right now it's completely broken. I could fix that and upgrade the `"gqless"` dependency, if that helps?

**Comment by PabloSzx** [comment]
@zenflow yes, this issue should be fixed with 1 condition, not mutating the variables object after using them, but if you send a new variable that serializes to the same previous value, they will be consider the same "selection"

**Comment by zenflow** [comment]
@PabloSzx 

> not mutating the variables object afters using them

That is a pretty reasonable expectation. 

> but if you send a new variable that serializes to the same previous value, they will be consider the same "selection"

Yesss that's exactly how I was expecting it to work!

I updated the reproduction and yeah I can confirm this issue is fixed! Amazing work!
