### ISSUE TITLE
Discussion: Writing your schema in the "gqless" way

### ISSUE THREAD

**Issue by adrianhunter** [gqless/gqless#106]
I want to put as much logic into my schema, models as possible. It makes sense to use typescript for that, but https://github.com/MichalLytek/type-graphql Already has so many decorators, I think it get's hard to read if you introduce even more decorators for custom logic. 

So, instead of writing your schema like this:
```ts
@ObjectType()
class Recipe {
  @Field(type => ID)
  id: string;

  @Field()
  title: string;

  @Field(type => [Rate])
  ratings: Rate[];

  @Field({ nullable: true })
  averageRating?: number;
}
```
why not just:
```ts
class Recipe {
  id: ID;
  title: string;
  ratings: Rate[];
  averageRating?: number;
}
```

I'm actually doing that right now in a little framework that I'm working on. I have a models folder with a tsconfig.json that has some custom transformers in it, using "ttypescript". I just say that all the default exports in all the files in the models folder should get converted to a dgraph GraphQL schema (https://graphql.dgraph.io/docs/quick-start/). So the only decorators that I'm using are the same as in dgraph. 

I can also transform this typescript schema easily into a gqless extension. I can say that a createdAt field is a readonly and it appears in the extension (So you get a typescript error if you want to update the cache). I also use "tstemplate" and "tsquery" to create all the "set" fields that will automatically make the mutation after the cache got updated. 

One could also write the @auth logic for dgraph with gqless, see: https://graphql.dgraph.io/docs/quick-start/

Any thoughts on that?

**Comment by samdenty** [comment]
gqless extensions are for adding client-only fields to the client. I'm not sure how this fits in type-graphql - as that's only used server side.

> I can say that a createdAt field is a readonly and it appears in the extension
createdAt, so you get a typescript error if you want to update the cache

I could see this being useful - but it would require a more advanced extensions API (to intercept cache updates).

Maybe something along the lines of:

```ts
const User = {
  createdAt: {
    [CACHE_UPDATE]() {
      throw new Error();
    },
    [CACHE_UPDATE]: false,
  },
};
```

**Comment by adrianhunter** [comment]
I mean that my transformer will generate the client extensions, it will not be used on the server side and I have my own solution, nothing to do with type-graphql. To let my IDE know it's a readonly field I have to use Classes in the extensions. 

```ts
class SomePost {
  readonly createdAt: Date;
}

export const Post = (user) => new SomePost();
```
I don't need any gqless changes or new features for that. Making It read only is enough for me, If I really call it, the backend will complain. 

I just wanted to talk about the Idea of writing your schema in this special way, there is no need to change anything in gqless to make that possible. It's just an Idea to write even less code in your backend. I do this also with my resolvers, instead of defining my input and return types in graphql, my transformer scans my typescript code and automatically creates graphql types and puts them into the main schema. 

I wanted to talk about what a "gqless" way of writing your backend could look like. We can also create a lot of gqless client code from that.

**Comment by PabloSzx** [comment]
Hi @adrianhunter, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
