### ISSUE TITLE
codegen with local schema

### ISSUE THREAD

**Issue by benmccann** [gqless/gqless#116]
https://gqless.dev/docs/getting-started#codegen has a `url` field. I'm interested in using a schema that I have on the local file system

**Comment by MaxmaxmaximusGitHub** [comment]
@benmccann as a workaround, write a server to express that will return data from the schema file)

**Comment by PabloSzx** [comment]
Hi @benmccann, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
