### ISSUE TITLE
[BUG] Update function not react to array length change

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [gqless/gqless#122]
```jsx
const Chat = graphql(() => (
  <ul>
    {query.messages.map(message => (
      <li key={message.id}>{message.text}</li>
    ))}
  </ul>
))

// this apply
setInterval(() => {
  update(query, {messages: [ {id: 0, text: "Hello"} ]})
}, 1000)


// this not apply
setInterval(() => {
  update(query, {messages: [ {id: 0, text: "Hello"},  {id: 1, text: "World"} ]})
}, 2000)
```

**Comment by MaxmaxmaximusGitHub** [comment]
oh, i see:

![image](https://user-images.githubusercontent.com/60403187/84784508-1146fc80-aff3-11ea-94cc-7013abeea3c4.png)

**Comment by PabloSzx** [comment]
Hi @MaxmaxmaximusGitHub, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
