### ISSUE TITLE
Path to schema in config

### ISSUE THREAD

**Issue by lastmjs** [gqless/gqless#123]
In the configuration, it would be nice to have the option to specify a path to a schema file instead of always having to have a running GraphQL API. I'm not sure if this is already possible. My use case is using gqless for a server-side application, where the server itself is executing GraphQL queries. I have my schema file readily available in the same project, so it would be nice to not have to have the GraphQL API running to generate the gqless stuff.

**Comment by PabloSzx** [comment]
Hi @lastmjs, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
