### ISSUE TITLE
Uncaught thrown promise

### ISSUE THREAD

**Issue by cdaringe** [gqless/gqless#141]
# Problem

When executing a query via `gqless/react`, a Promise is thrown against expectation:

```js
// http://localhost:8080/web_modules/@gqless/react.js
    if (promise) {
      let resolved = false;
      promise.then(() => resolved = true); // We can't directly throw the promise, otherwise
      // child components (with data requirements) won't
      // render - meaning multiple requests
      //
      // To prevent this we instead return a Fragment,
      // which contains a component that throws the Promise.

      const Suspend = () => {
        // This is necessary to prevent an infinite loop
        if (resolved) return null;
        throw promise; // HERE  ⏪⏪⏪⏪⏪⏪
      };

      return v(p, null, returnValue, v(Suspend, null));
    }
```

This occurs directly off of my main `render`. FWIW, my stack isn't the usual. I'm using `preact` w/ react-compat, and snopack.

Here's the associated component:

```tsx
import { FunctionalComponent, h } from "preact";
import { query } from './gqless'
import { graphql } from '@gqless/react'


const Checklist: FunctionalComponent = graphql(() => {
  return (
    <div>{JSON.stringify(query.node_types.map(t => t.id), null, 2)}</div>
  );
})

export default Checklist;
```

If i do _nothing interesting_ in my query, e.g. `query.__typename`, which is probably statically known in the generated schema, no such error is thrown.

**Comment by PabloSzx** [comment]
Hi @cdaringe, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
