### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by taviroquai** [gqless/gqless#148]
Hi guys,

Thanks for the new version.

I'm getting an error while trying to generate the gqless schema files.

```bash
$ npx gqless generate
TypeError: Cannot read property 'name' of undefined
```

You can reproduce with the following demo:
https://github.com/taviroquai/test-db2graphql-gqless

Thank you so much!

**Comment by PabloSzx** [comment]
![image](https://user-images.githubusercontent.com/8672915/112237607-c7deaa00-8c21-11eb-9731-e1ff8fdff1d1.png)

You are using old versions of gqless

**Comment by taviroquai** [comment]
@PabloSzx thank you, my fault.

I fixed it now.

Now there is another error when trying to run the app. It looks like its missing generating some types. Any ideas please?

![image](https://user-images.githubusercontent.com/498409/112242312-7d6e2500-8c43-11eb-87a6-4d9148b91090.png)

**Comment by PabloSzx** [comment]
![image](https://user-images.githubusercontent.com/8672915/112243578-94ede380-8c2c-11eb-9853-210a33f96e2e.png)

all I can get is this

**Comment by PabloSzx** [comment]
I had to update "knex" and "pg" modules.

This is the reason of this not working:

![image](https://user-images.githubusercontent.com/8672915/112244788-8274a980-8c2e-11eb-99e9-2d8a83d4e095.png)

**Comment by PabloSzx** [comment]
I will add installing "graphql" in the docs and setting it as peer dependency where it's needed, thanks for reporting it @taviroquai
