### ISSUE TITLE
useQuery returns proxy

### ISSUE THREAD

**Issue by nemanjamilosavljevic-newtron** [gqless/gqless#151]
I have a very simple setup (basic) and the correct configuration (src/gqless/index.ts and schema.generated.ts are generated).
However, when I try to destructure the `useQuery`, I get no suggestions as to what there is.
When I log the output of the `useQuery`, it returns the `Proxy`.
![image](https://user-images.githubusercontent.com/77624664/112370183-5d8b3f80-8cdd-11eb-8b7d-70b7ace7a2c8.png)

And even if I try to manually access a property, for example, `findAdminDivisionsUsingGET`, this returns a `Proxy` as well.

Is this an expected behavior?

**Comment by PabloSzx** [comment]
> And even if I try to manually access a property, for example, `findAdminDivisionsUsingGET`, this returns a `Proxy` as well.
> 
> Is this an expected behavior?

In `gqless` anything that isn't a scalar is a proxy, and the proxies are meant to be passed around, and the components/code that require some scalars from it, simply request it (or simply use it in the same place you created it).  Keep in mind that all the real data in GraphQL is kept in the scalars, everything else is just structure, and that's is by spec, you have to specify the scalars you want from a query

**Comment by nemanjamilosavljevic-newtron** [comment]
Thanks for the fast replay.
Okay, got it.
 
Well, the thing is, this is a CRA with typescript, and this `const { me, users } = useQuery();` isn't happening for me.
Shouldn't the `me` and `users` be suggested when destructuring the `useQuery`?
It's kind of hard to have an idea of what can be found inside something when this is the response
![image](https://user-images.githubusercontent.com/77624664/112378837-b364e500-8ce7-11eb-9641-50e3d26015d2.png)

To get to this place I had to find out from the first response that there is the e.g. `findCitiesUsingGET` inside.
Then I did something like this to access `data`
```ts
  const { findCitiesUsingGET } = useQuery();
  console.log(findCitiesUsingGET()?.data);
```
Only to get a response like from the picture above.

Is there documentation regarding the usage other than the `helloWorld`?

**Comment by PabloSzx** [comment]
You should have auto-completion in your code editor, could you create a reproduction repo of the issue?

If you destructure useQuery you can access all the possible queries your API offers, and simply following the structure, you get the data, console logging the proxies will never make any sense for proxies, but you can JSON.stringify(your_proxy) and it will output the cache associated to your selection.

**Comment by PabloSzx** [comment]
> Is there documentation regarding the usage other than the `helloWorld`?

We have a sandbox created to play with gqless without needing to install anything: https://codesandbox.io/s/gqless-in-nextjs-example-g2mib?file=/src/pages/singleUser.tsx. I added a couple of examples of dealing with objects.

We will add more "Real-world" examples down the line

**Comment by nemanjamilosavljevic-newtron** [comment]
Okay, I will first check this codesandbox out and see if it will shed some light on the usage.

**Comment by nemanjamilosavljevic-newtron** [comment]
I will gladly close this issue.
The problem was my local setup with the root of this project being nested within another project (this was a demo where I was testing it), but opening it in a dedicated IDE resolved the tsconfig correctly and thus the types of the gqless.

**Comment by PabloSzx** [comment]
No problem 👌

And btw, I'm working in a interactive way of playing with gqless with a playground API from within gqless.com, way better than codesandbox in terms of performance and editor resemblance to actual code editors
