### ISSUE TITLE
SSR Issue

### ISSUE THREAD

**Issue by yovanoc** [gqless/gqless#158]
![image](https://user-images.githubusercontent.com/7302317/112527802-b9b89700-8da3-11eb-909f-6197c6380787.png)

https://gist.github.com/yovanoc/e2d8861205f21eca139a56acd7481881

A page with a useRouter() fail in the react-ssr-prepass

**Comment by PabloSzx** [comment]
thanks for reporting this issue, will look into it

**Comment by PabloSzx** [comment]
The solution is a little bit ugly, but I can't see any other alternative, since with prepareReactRender we are rendering outside of the Next.js render tree:

```ts
import { RouterContext } from 'next/dist/next-server/lib/router-context';
import { Router } from 'next/router';

export const getServerSideProps: GetServerSideProps<PropsWithServerCache> = async () => {
  const { cacheSnapshot } = await prepareReactRender(
    <RouterContext.Provider value={Router as any}>
      <RefetchPage />
    </RouterContext.Provider>
  );

  return {
    props: {
      cacheSnapshot,
    },
  };
};
```

**Comment by PabloSzx** [comment]
Added some comments about how to handle this https://gqless.com/react/ssr#using-nextjs-router
That isn't a perfect solution, but we can't have one, since in the functions we don't have access to the router, and it's not even created yet by Next.js
