### ISSUE TITLE
[FEATURE] add support  schema.json file type

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [gqless/gqless#177]
![image](https://user-images.githubusercontent.com/69426460/113858678-ae566a00-97ac-11eb-9b13-0825410862f8.png)

![image](https://user-images.githubusercontent.com/69426460/113858724-bd3d1c80-97ac-11eb-878d-418cacad0cf2.png)

![image](https://user-images.githubusercontent.com/69426460/113858872-e9f13400-97ac-11eb-83de-8668d72f5ae9.png)

![image](https://user-images.githubusercontent.com/69426460/113858745-c3cb9400-97ac-11eb-9102-033fdf97d618.png)

**Comment by PabloSzx** [comment]
Thank you for the suggestion, when #176 is merged, this feature is going to be available, it should be merged later today
