### ISSUE TITLE
TS2303: Circular definition of import alias 'createClient'.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [gqless/gqless#184]
"gqless": "^2.0.11",
		"@gqless/react": "^2.0.13",
		"@gqless/subscriptions": "^1.0.10",
		"typescript": "^4.2.4"

![image](https://user-images.githubusercontent.com/69426460/114037985-25156500-988a-11eb-8589-c2865c8c2487.png)

jsconfig.json
```json
{
	"compilerOptions": {
		"target": "es5",
		"lib": [
			"dom",
			"dom.iterable",
			"esnext"
		],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": false,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"baseUrl": ".",
		"paths": {
			"@components/*": [
				"components/*"
			]
		}
	},
	"include": [
		"next-env.d.ts",
		"**/*.ts",
		"**/*.tsx"
	],
	"exclude": [
		"node_modules"
	]
}
```

**Comment by PabloSzx** [comment]
because of your "baseUrl", the generated "gqless" folder is conflicting with the gqless library itself, I think the best solution would be to change the destination of the generated file to another place

**Comment by MaxmaxmaximusAWS** [comment]
I change it to `./graphql`, thanks =)
