### ISSUE TITLE
[TypeError: originalType.toConfig is not a function]

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [gqless/gqless#185]
"gqless": "^2.0.11",
	"@gqless/react": "^2.0.13",
	"@gqless/subscriptions": "^1.0.10",
	"typescript": "^4.2.4"

```
$ gqless generate
[TypeError: originalType.toConfig is not a function]
```

how i can see error stack to get it you?

**Comment by PabloSzx** [comment]
what is the version of "graphql" you have?

**Comment by MaxmaxmaximusAWS** [comment]
oh, i install 14 version =)
now i change it to 		"graphql": "^15.5.0", and all works, thanks
