### ISSUE TITLE
[BUG] I use gqless by nodejs api and "gqless.config.cjs" creating every time, but shouldn't

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [gqless/gqless#203]
1) delete gqless.config.cjs from you project
2) create script.js file:

```js
  const { inspectWriteGenerate } = require('@gqless/cli')

  inspectWriteGenerate({
    endpoint: "http://localhost:3000/api/graphql",
    destination: './src/graphql/index.ts',
  })
```

3) run `node script.js`

4) "gqless.config.cjs" creating automatically in root of project, but shouldn't

**Comment by PabloSzx** [comment]
this issue is going to be easy to fix, I already have an idea 👍
