### ISSUE TITLE
Errored queries don't log in logger

### ISSUE THREAD

**Issue by natew** [gqless/gqless#207]
When running the logger, if my api returns non-json, I get this error *and no log*. Because it doesn't show query/variables, it's a bit harder to see easily where it happened:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/12100/114969129-a2158100-9e2c-11eb-8680-0cc2ec3b5034.png">

**Comment by PabloSzx** [comment]
That logic should be located in the `QueryFetcher`, have you tried verifying the data there?. If the issue is still there a reproduction would be appreciated
