### ISSUE TITLE
Automatic refetching

### ISSUE THREAD

**Issue by implosivemosaic** [gqless/gqless#209]
This library seems awesome!

Using [your code sandbox](https://gqless.com/contributing) I wanted to understand what options your library provides in regards to automatically refetching data from the server but I couldn't quite figure it out. I tried playing with `useQuery()` and the `staleWhileRevalidate` options -- my NextJS project is [using `useSWR`](https://swr.vercel.app/) and I am curious what the right approach would be with gqless.

**Comment by PabloSzx** [comment]
gqless currently offers "staleWhileRevalidate" behaviour while using the React bindings:

- Check React Configuration https://gqless.com/react/config
- Check React "Fetch Policy" https://gqless.com/react/fetching-data#fetch-policy, the equivalent for stale-while-revalidate is "cache-and-network", this policy can be specified in a couple specific hooks, in others you are are restricted to use the simpler "staleWhileRevalidate".


If you are using the Core, outside of React, it's possible to have the replicate the behavior using resolved options https://gqless.com/client/api/interfaces/resolveoptions or high extra logic + "refetch" https://gqless.com/client/fetching-data#refetching-data

**Comment by implosivemosaic** [comment]
Thank you that helped clarify things and I can see SWR working properly now! It looks like you also have a polling implementation exposed by `useTransactionQuery()` so now I just need to play with your library to see how it complements / replaces the need for our current use of `useSWR`. I'll close this issue but for anyone reading, I'd be interested in any examples or further advice regarding the use of this library in combination or as a replacement to `useSWR`.
