### ISSUE TITLE
useSubscription: only first use of hook returns data

### ISSUE THREAD

**Issue by vasyas** [gqless/gqless#216]
Reproducible demo in CodeSandbox:
https://codesandbox.io/s/mystifying-payne-0un5y
The server part is forked from GQLess example, the web part is written from scratch.

I have an app using React / React Router.
App has 3 pages: Home | Users | Groups with navigation between them.

UsersPage  calls `useSubscription` to get data:
```
  const subscription = useSubscription()
  return <div>Users: {subscription.users[0].name}</div>
```

GroupsPage is the same but uses a different subscription.

The problem is that only the first `useSubscription`, counting from the opening site in a browser works:
https://monosnap.com/file/Hblflww8n8Trbk0n3yW76d0sJgCMXA

All subsequent subscriptions return skeleton data.

The server sends subscribed data as expected.

**Comment by Ramilito** [comment]
I have the same issue, using nextjs (11) and react(17).
When I remove one of them the other works and vice versa

**Comment by vasyas** [comment]
This bug is a show-stopper for me, and I would like to contribute a PR to get it fixed.
But I cannot isolate a section of the source code where the bug should be.
@PabloSzx any guidance here?

**Comment by PabloSzx** [comment]
After updating the versions to `
    "@gqless/react": "2.0.15",
    "gqless": "2.0.14",
`

this issue doesn't seem to exist, the versions in the sandbox were very old

Anyways, further development is going to be made in the new repository/package name **GQty** https://github.com/gqty-dev/gqty https://gqty.dev

**Comment by PabloSzx** [comment]
In the new gqty release I'm going to add some extra logic that should prevent any issue with the subscription hook
