### ISSUE TITLE
Separate endpoint and schema in configuration

### ISSUE THREAD

**Issue by divyenduz** [gqless/gqless#217]
Just tried gqless and what an amazing experience, wow 🙌 

I have a feature request that I am willing to contribute. I would like to use pre-generated `schema` in development but have GraphQL endpoint already in `queryFetcher` (vs modifying the generated file). I would like to treat the generated file as an untouchable artifact with the default generated client. 

Is this already possible somehow? If no, I would like to make a few suggestions: 

1. With a variable on `client`, like `client._ENDPOINT` that would be generated in the default `index.ts` like 
```ts
// Modify "./graphql/generated/nexus/schema.graphql" if needed
const response = await fetch(client._ENDPOINT || '<schema from config>', {
```
2. In the default file, expose a client constructor like that allows overriding the endpoint.

I am aware that I can construct the whole client myself by writing minimal code like so but just having this option configurable (and maybe some more in future) would spare me from all the boilerplate. 

<details>
<summary>Code sample</summary>

```
import { createClient, QueryFetcher } from 'gqless'
import { createReactClient } from '@gqless/react'
import {
  GeneratedSchema,
  SchemaObjectTypesNames,
  SchemaObjectTypes,
  generatedSchema,
  scalarsEnumsHash,
} from '../graphql/generated/gqless/schema.generated'

const queryFetcher: QueryFetcher = async function (query, variables) {
  const response = await fetch('http://localhost:3000/api/graphql', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query,
      variables,
    }),
    mode: 'cors',
  })

  const json = await response.json()

  return json
}

const client = createClient<
  GeneratedSchema,
  SchemaObjectTypesNames,
  SchemaObjectTypes
>({
  schema: generatedSchema,
  scalarsEnumsHash,
  queryFetcher,
})
const reactClient = createReactClient(client)
const { useQuery: useGQuery } = reactClient
```
</details>

What do you think?

**Comment by PabloSzx** [comment]
I don't think I understand the issue, the gqless cli generated 2 files, the schema one is the only one that is not intended to be modified, but the other one with the client you can modify it at will, there are plenty of comments in the file itself mentioning it, there you can/HAVE to modify stuff, like the query fetcher with the endpoint

**Comment by divyenduz** [comment]
What I want to achieve is rapid iteration workflow. So, I don't have to modify the generated file that HAS to be modified but I can configure it once and run `gqless generate` multiple times.

**Comment by PabloSzx** [comment]
@divyenduz 

Now I think I understood, previously in a couple versions ago there was the config ".endpoint" that would change the default endpoint, but that just meant that in 99% percent of the time the endpoint had to be manually changed anyways and it was decided to be removed to just encourage the manual modification of the generated client file, then, the schema thing, that's very different, there is no way for the cli to be able to generate the types on runtime and typescript to pickup the types (typescript is static typing), you can call [`generate`](https://gqless.com/cli/programmatic#generate)  programmatically, and that will get you the runtime artifacts for gqless and you could use it in runtime, and you could do use gqless without the automatic typing, that flow is actually used in some of the tests implemented, but using it in actual environments doesn't make sense if you don't have type-safety/auto-completion.

Now, on the feature request in specific, I feel it's completely possible to make something more dynamic using the programmatic API of the CLI https://gqless.com/cli/programmatic, and you are free to experiment with it, and even open a PR to create a new feature for the CLI, but right now working on it is very unlikely as I don't have any free time to work on gqless.

**Comment by divyenduz** [comment]
Thank you, as I mentioned in my first comment, see "Code Sample", I have a workaround already. I use that with the following command to re-generate

```
"gqless:generate": "rm -rf ./grapqhl/generated/gqless && gqless generate"
```

I was thinking if we can expose an API to not require so much boilerplate but it is totally fine for now. 

If this workflow has been considered before, feel free to close this or keep it open as a feature request. I am happy to help with a contribution if we can decide on an API for this use case.

**Comment by PabloSzx** [comment]
then I will close this issue as I won't be able to work on this specific feature, but PRs are open.
