### ISSUE TITLE
Export mutation/query argument types

### ISSUE THREAD

**Issue by egoist** [gqless/gqless#218]
In following [example](https://gqless.com/react/mutations#example):

```ts
const [login, { isLoading, data, error }] = useMutation(
    (mutation, args: { email: string; password: string }) => {
      const { user, error } = mutation.login({ args });
    },
  )
```

You're manually typing the `args`, I guess it's probably a good idea to export the mutation/query argument types in `schema.generated.ts` so we can reuse it?

**Comment by PabloSzx** [comment]
yeah, this a missing piece, and this issue is related to #178

**Comment by egoist** [comment]
Nice 👌, I guess this issue could be closed then.
