### ISSUE TITLE
Using custom scalarTypes doesn't work.

### ISSUE THREAD

**Issue by nemonemi** [gqless/gqless#229]
When trying to pass a custom scalar to the list of scalar types, it complains about the type.

```cjs
Warning, invalid config scalarTypes, got: {"DateTime":"DateTime"}, expected "object of strings". {"DateTime":"string"} used instead.
```

```cjs
// gqless.config.cjs
var scalars = require('graphql-scalars');
/**
 * @type {import("@gqless/cli").GQlessConfig}
 */
const config = {
  enumsAsStrings: false,
  react: true,
  scalarTypes: { DateTime: scalars.GraphQLDateTime },
  preImport: '',
  introspection: {
    endpoint: '../../../apps/bd/api/generated-schema/schema.graphql',
    headers: {},
  },
  destination: './src/gqless/index.ts',
  subscriptions: false,
};

module.exports = config;
```

**Comment by nemonemi** [comment]
Please disregard this issue, the path to the config is wrong, however, the message could have been more informative...

**Comment by PabloSzx** [comment]
The scalar types is only the an object of strings, the type is Record<string,string>, that is because it's only the string that is added as the type (the name of the string) in the pre-generated schema

**Comment by PabloSzx** [comment]
further development is going to be made in the new repository/package name __GQty__ https://github.com/gqty-dev/gqty
