### ISSUE TITLE
How to handle the error coming from the graphql server?

### ISSUE THREAD

**Issue by nemonemi** [gqless/gqless#231]
I am accessing a resource by `ID` which doesn't exist. A reasonable use case.
However, I am not sure how to handle this. 
In the `onError` callback of the `useQuery` I'm getting this message: `Error: GraphQL Errors, please check .graphQLErrors property`

I'd like to get feedback that the access to data with this ID is invalid so that I could toggle my form between creation and updating, for example.

**Comment by nemonemi** [comment]
@samdenty, 
the graphql endpoint, tested in the graphiql, resolves the update request without any errors.
What could be the cause for the `gqless` to complain?

**Comment by PabloSzx** [comment]
As the error mentions, when there is more than a single error in a query there is no perfect solution to show them all, that is why when that happens you have to access the ".graphQLErrors" to get the list of errors

```ts
onError(error) {
  console.error(error.graphQLErrors);
 for (cont err of error.graphQLErrors) {
   // err is every error 
 }
}
```
