### ISSUE TITLE
polling only windows/tabs on focus

### ISSUE THREAD

**Issue by raymclee** [gqless/gqless#232]
is it possible to set the polling only when windows/tabs is focused like react-query/swr does?

**Comment by PabloSzx** [comment]
This feature has been added to `useTransactionQuery` in `gqty` https://github.com/gqty-dev/gqty https://gqty.dev 🎉

**Comment by PabloSzx** [comment]
now by default polling is disabled on background, but can be enabled with a new option called "pollInBackground"
