### ISSUE TITLE
How to refetch after mutation when the query initially returns null

### ISSUE THREAD

**Issue by samwoolertonFosters** [gqless/gqless#234]
I have a component to sign on or off a job site. Signing off from being on the site works perfectly, as the `query.activeVisit` goes from having a value to being `null` and the component re-renders.
Signing onto the job site doesn't work as cleanly though: `gqless` doesn't refetch as `query.activeVisit` started out as null.
I've tried using `staleWhileRevalidate` option but not sure how to configure it (passed an object and updated a property when the mutation finished but that did nothing). Have also tried using `useRefetch` and calling `refetch(query.activeVisit)` but that did nothing too (tried using `.then` as it returns a promise and confirmed that it returns the value but I need it to update `query.activeVisit`.

I expect I could fall back to holding `activeVisit` in `useState` and update it more manually, but I expect there's a better way to do this.
What's the recommended approach here?

**Comment by PabloSzx** [comment]
the "refetch" function you have two options, give a function that does the access:

```ts
refetch(() => {
   query.activeVisit
})
```

or give an entire proxy to the function

```ts
// this will refetch every query you have made so far
refetch(query)
```

 further development is going to be made in the new repository/package name **GQty** https://github.com/gqty-dev/gqty

**Comment by felquis** [comment]
I'm facing similar issue, first load it returns no data, then I send a create mutation and I do refetch when the promise is fulfilled, but immediately I see the console `Warning! No data requested` then if I do a full reload in the page the query returns the data properly. But I can't find more literature about this warning.
