### ISSUE TITLE
TODO: Blog post

### ISSUE THREAD

**Issue by samdenty** [gqless/gqless#43]
Emphasize it is a standalone GraphQL client, alternative to Apollo/Relay. Built to be used in complex applications the size of Discord.

Emphasize the reactivity, components are selectively updated - similar to using MobX. Emphasize being able to observe values

Emphasize the extensions, the ability to add client-only state to your endpoint. Being able to convert date strings into Date objects, automatically. Being able to create custom abstractions, essentially your own custom SDK.
Being able to compute fields, from other fields if they're already fetched - if not just fetching.

Emphasize the ability to orchestrate how queries are fetched at runtime, without manually modifying queries. The ability to perform A/B tests etc.

Emphasize the dev tools. With normal clients you feel like your separated from your endpoint, having to open up a playground to see data. Emphasize being able to log an object - see it's fields, update it, and fetch additional fields on it.

Emphasize the 100% type safety, within your whole app. The instant feedback, inline documentation, find-all references

Emphasize the 'smart objects'. Always having the current version of the data throughout your entire application. Emphasize the power it gives you, ie. React hooks.

Emphasize being able to update the cache, just by having a reference to the data you want to update. No manual updating of a cache store

Emphasize how flexible the cache is. Being able to link any parts of it together.

Emphasize the abilty to create custom abstractions, without modifying the internals. Eg. Poller 

Emphasize how well it works with suspense, the ability to have progressive loading states

Emphasize how it tries to reduce data fetching. Fetching the single fields it needs + fields required to ID a type. If the returned ID changes - it sends out another request to re-fetch everything

**Comment by potatopotaro** [comment]
Hey @samdenty 

I just wanted to say that I think you're onto something with `gqless`. Graphql clients are starting to create a ton of boilerplate. Getting good publicity for `gqless` is a fantastic way to find more maintainers and get help. Cheers.

**Comment by JoeSchr** [comment]
With the new [composition-api (equivalent to react hooks)](https://vue-composition-api-rfc.netlify.com/#type-issues-with-class-api)  and [graphql-code-generator](https://graphql-code-generator.com/docs/plugins/typescript-vue-apollo)  you have any plans to support Vue? That would be awesome!

I think you are really on to something here. [I have been feeling that handling gql on client side while great is also needlessly verbose](https://github.com/vuejs/vue-apollo/issues/140#issuecomment-451658555)


Anyway really great work! 👍

**Comment by one-aalam** [comment]
Hey @samdenty 

This is groundbreaking and will lead to a very maintainable code on the UI side IMO. All kind of verbosity we're witnessing in different GraphQL libraries are there so that things are explicit, known and conforming to some interface and have its place but there's a definitely a category of applications that don't need all of that and this library seems to be a perfect fit!

Great Work 👍

**Comment by adrianhunter** [comment]
@JoeSchr Maybe you want to have a look into svelte if you like to write less code. I was able to build a minimal Query component and it just works out of the box with svelte. 

the complete component:
```html
<script lang="typescript">
  import { resolved } from "gqless";
  let _$$props = $$props;
  async function resolveData(_) {
    await resolved(
      () =>
        _$$props.$$slots && _$$props.$$slots.default[0](_$$props.$$scope.ctx)
    );
  }
</script>

{#await resolveData($$props) then value}
  <slot />
{/await}

```

An example with updating the cache and changing some query params:
```html
<script lang="typescript">
  let value = 0;
  $: filter = {
    limit: 10,
    where: { hash: { _ilike: `${value}%` } }
  };
  $: txs = query.tx(filter);
</script>

<input type="text" bind:value class="input" placeholder="search hash" />

<button
  on:click={() => {
    txs[0].hash = 'asd';
  }}>
  change hash
</button>

<Query>
  {#each txs as item}
    <div>{item.firstSeen} : {item.hash}</div>
  {/each}
</Query>

```

**Comment by ticruz38** [comment]
@adrianhunter would you mind sharing a complete gist or repository with your example, it does looks awesome!

**Comment by adrianhunter** [comment]
Ah, I can post a minimum example here. Do you know svelte? My project is still not ready to share. I also use parcel. If you are interested in the typescript stuff, just create a svelte.config.js with:
```js

const autoPreprocess = require("svelte-preprocess");

module.exports = {
  dev: process.env.NODE_ENV !== "development",
  preprocess: [
    // Foo(),
    autoPreprocess({
      typescript: {
        compilerOptions: {
          target: "es2020",
          module: "es2020",
          baseUrl: "./src",
        },
        transpileOnly: process.env.NODE_ENV !== "production",
      },
    }),
  ],
};


```
create src/index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <meta name="viewport" content="width=device-width" />

  </head>

  <body>
    <div id="app"></div>

    <script src="main.ts"></script>
    </script> 
  </body>
</html>

```

src/main.ts

```js
import App from "./App.svelte";

const app = new App({
  target: document.querySelector("#app"),
});

export default app;

```
install npm module "parcel-plugin-svelte"

start your app with parcel src/index.html

and use gqless and documented + my query component

Let me know if that works. 

I'm working on a svelte full stack framework that uses dgraph's upcoming native graphql features and many more stuff

**Comment by adrianhunter** [comment]
Ah, and If you want to get a working but not perfect type checking in your markup, install this:
https://marketplace.visualstudio.com/items?itemName=halfnelson.svelte-type-checker-vscode

crazy how simple that sounds, I can't believe that was all to get typescript working with svelte + markup type checking. I spend so much time to find the right way to do that. also first dig deep into snowpack stuff with svelvet

**Comment by ticruz38** [comment]
I've been playing around all day, svelte and gqless seems like a great fit, I got it working with rollup. Typescript however is quite a pain with svelte, thanks for your tips! I'll definitely check this out!

**Comment by adrianhunter** [comment]
@samdenty the gqless/react implementation seems rather complex compared to my simple Query component. Do I miss some Important details here? Svelte has the nice feature that it's already reactive by assigning new values to any vars in the $: context. So just calling txs[0].hash = 'asd'; does work out of the box. You probably had do code some magic to get this working in react?

**Comment by adrianhunter** [comment]
@ticruz38 I realized that github somehow removed 1 $ sign from my component?!

this is correct:

<script lang="typescript">
  import { resolved } from "gqless";
  let _$$props = $$props;
  async function resolveData(_) {
    await resolved(
      () =>
        _$$props.$$slots && _$$props.$$slots.default[0](_$$props.$$scope.ctx)
    );
  }
</script>

{#await resolveData($$props) then value}
  <slot />
{/await}

**Comment by ticruz38** [comment]
> @samdenty the gqless/react implementation seems rather complex compared to my simple Query component. Do I miss some Important details here? Svelte has the nice feature that it's already reactive by assigning new values to any vars in the $: context. So just calling txs[0].hash = 'asd'; does work out of the box. You probably had do code some magic to get this working in react?

I did use it in svelte only, and it works very very well

**Comment by adrianhunter** [comment]
wooohooo. Nice!!!!!

**Comment by samdenty** [comment]
> the gqless/react implementation seems rather complex compared to my simple Query component

React integration does:

### Query tracking
Performs gqless `scheduler.beginQuery` at the start of a component, so you have the ability to orchestrate into custom queries.

### Reactive updates
Tracks the exact data you access between renders, installing/removing react state update hooks.

### Suspense
Has logic to do a "silent" render of your application, whilst suspending your application.
Uses all the available events from Accessor, so it works in complex cases.

**Comment by PabloSzx** [comment]
Hi everyone, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 .
