### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by lishine** [gqless/gqless#47]
Will there be subscriptions?
Does the polling practically makes subscriptions unnecessary?

**Comment by samdenty** [comment]
There will be

When they, polling / (un)subscribing will be done under the hood for you. It'll automatically detect the fields to subscribe to etc.

**Comment by PabloSzx** [comment]
Hi @lishine, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
