### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by lukejagodzinski** [gqless/gqless#51]
Hi! Thanks for the great package!

I was searching for information about how to perform mutations and I've just realized that it's work in progress. Any expected date of release? I would like to ditch Apollo Client :) and this library is one of the best things that happen for the client side GraphQL in a while.

**Comment by lukejagodzinski** [comment]
Also if you need any help with programming I might dedicate some of my free time to this project :)

**Comment by samdenty** [comment]
This is highly dependent on the GQLess compiler

The API I'm planning for (transformed using the compilers Babel plugin):

```ts
const data = await mutation.signIn({ email,  password })

console.log(data.token, data.user.fullName)
```

**Comment by lukejagodzinski** [comment]
Yeah the syntax is what I would expect it to be. However, is it required to use Babel plugin to achieve that? How much time do you think it would take and what are steps required to implement it? Maybe people (including me) could help with that if there is a list of things to do.

It's funny, when I saw your library yesterday I was like "wow that's almost exactly what I wanted to create" :). Maybe the only difference would be no use of Proxies. But tbh I think that if you release stable version of this library, then in one year from now anyone starting a new project with GraphQL will use your library instead of Apollo. It's just a nail into Apollo's coffin 😜

**Comment by lukejagodzinski** [comment]
Also little update for someone who wants to use API similar to official one. Just create file called `mutation.ts` and fill it with content similar to this:

```ts
import { fetchQuery, Mutation } from "{outputDir}";
import { QueryResponse } from "gqless";

const mutations = {
  signIn: `
    mutation SignIn($email: String!, $password: String!) {
      signIn(email: $email, password: $password) {
        token
        user {
          id
          fullName
        }
      }
    }
  `,
};

const signIn = async (variables: Parameters<Mutation["signIn"]>[0]) => {
  const result = await (fetchQuery(mutations["signIn"], variables) as Promise<
    QueryResponse<{ signIn: ReturnType<Mutation["signIn"]> }>
  >);
  return result.data.signIn;
};

export const mutation = {
  signIn,
};
```

Wanted to create something more generic but TS didn't want to cooperate :)

**Comment by kpfromer** [comment]
This package is crazy cool! Regarding mutations, could there be a section on the documentation website written about using mutations (using the above method) temporarily before 1.0 is released? I can create a pull request to do that if that is something that you want to be done. Again, this is a fantastic package and agree with @lukejagodzinski about it being an Apollo killer.

**Comment by PabloSzx** [comment]
I was experimenting and I was able to make a mutation hook that uses all the type-safety already generated. 

The problem is that TypeScript generics via hooks don't work as expected, and this should be added manually (or generated in **gqless generate**) in **src/graphql/client.ts** to work properly.

[Here is the code](https://github.com/PabloSzx/Next.js-TypeGraphQL-gqless/blob/useMutation/src/graphql/client.ts#L36) that has to be added in the generated file.

And [Here](https://github.com/PabloSzx/Next.js-TypeGraphQL-gqless/blob/useMutation/pages/index.tsx#L8) is the usage in React.

Looks like this
```tsx
const [mutation, { state, data }] = useMutation(schema =>
      schema.mutateHelloWorld({
        asd: "zxc"
      })
    );
```
state is  "waiting" | "loading" | "error" | "done", data the resulting data, and mutation is a function that returns a promise of the data

**Comment by lukejagodzinski** [comment]
@PabloSzx nicely done. I will definitely try that before official support. Thanks!

**Comment by PabloSzx** [comment]
@lukejagodzinski I just released a library that uses this logic, but much more refined https://github.com/PabloSzx/gqless-hooks

**Comment by lukejagodzinski** [comment]
@PabloSzx thanks I will probably use that but it would also be great if there is an official `@gqless/hooks` package. So maybe you guys could collaborate on that?

**Comment by PabloSzx** [comment]
Of course I'd like to help :smile: the thing is, there are already some pull requests on the hold :eyes: and at first glance I think the design of these hooks are not the ideal design @samdenty was thinking about, since are not Suspense based :man_shrugging: .

**Comment by lukejagodzinski** [comment]
I think that using Suspense is not a bad thing even though it's not stable feature. If you're going to use `gqless` in the first place you're already using Proxies which are not supported by IE and there is no good polyfill for that. So in some sense you're already using feature that might be problematic. Also after releasing Suspense, the React team said that now it's time for the packages authors to test it out so they can move it to stable release. So someone has to do that job to make it official. If there is really a need to have non-Suspense based hooks there could be a separate package for that in deed.

**Comment by veeral-patel** [comment]
@samdenty Hey - thanks for this library from me as well! How would I update the cache after a mutation?

**Comment by rhlsthrm** [comment]
Really liking this tool, planning to go all in on it on my current project and ditch Apollo and all its boilerplate. Any update on the status of official support for mutations? In the meantime, I'll use these workarounds.

**Comment by rhlsthrm** [comment]
@lukejagodzinski I'm trying your strategy but running into some issues. I'm using Hasura to generate my GraphQL endpoint, and when I generate gqless, it seems to give me something called `mutation_root` instead of `Mutation` in the generated schema. I'm trying to copy your code:

```
import { fetchQuery, mutation_root } from "./index";
import { QueryResponse } from "gqless";

const mutations = {
  linkAccount: `
    mutation LinkAccount($publicToken: String!, $userId: uuid!) {
      linkAccount(accountData: { publicToken: $publicToken, userId: $userId }) {
        message
      }
    }
  `
};

const signIn = async (variables: Parameters<mutation_root["linkAccount"]>[0]) => {
  const result = await (fetchQuery(mutations["linkAccount"], variables) as Promise<
    QueryResponse<{ linkAccount: ReturnType<mutation_root["linkAccount"]> }>
  >);
  return result.data.linkAccount;
};

export const mutation = {
  signIn
};
```

However I'm getting a type error on the `mutation_root["linkAccount"]`:

```
Type 'null | undefined' does not satisfy the constraint '(...args: any) => any'.
Type 'undefined' is not assignable to type '(...args: any) => any'.ts(2344)
```

Any ideas on how to fix this?

**Comment by samdenty** [comment]
I've been super busy recently, so no ETA yet. Have been working on the compiler -  which is a massive undertaking.

In theory I could get it to work for some basic use cases currently, but I still have a lot of work proving out how it works

**Comment by natew** [comment]
@rhlsthrm I'm using Hasura too but my `src/generated/types.ts` doesn't include mutation_root at all. It includes all the queries, and if I separately use graphql generator my schema.json shows all the mutations just fine.

**Comment by PabloSzx** [comment]
Hi @kpfromer, @veeral-patel & @rhlsthrm, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
