### ISSUE TITLE
Query more than 3 levels deep

### ISSUE THREAD

**Issue by taviroquai** [gqless/gqless#53]
Hi thanks for this library!

I'm getting an error when requesting data on "4rd level" field.

This is my graphql schema:

```gql
type Query {
  getFirstUsers(filter: String, pagination: String, where: Condition, _debug: Boolean, _cache: Boolean): Users
  getPagePosts(filter: String, pagination: String, where: Condition, _debug: Boolean, _cache: Boolean): PagePosts
}

type Mutation {
  putItemUsers(_debug: Boolean, input: InputUsers!): Users
  putItemPosts(_debug: Boolean, input: InputPosts!): Posts
}

type Users {
  id: Int
  username: String
  password: String
  firstname: String
  lastname: String
  posts(filter: String, pagination: String, where: Condition, _debug: Boolean, _cache: Boolean): PagePosts
  fullname(foo: String): String
}

type PageUsers {
  total: Int
  items: [Users]
}

type Posts {
  id: Int
  users_id: Int
  title: String
  categories_id: Int
  publish: Boolean
  users_id_users: Users
  categories_id_categories: Categories
}

type PagePosts {
  total: Int
  items: [Posts]
}

input Condition {
  sql: String!
  val: [String!]!
}
```

This is the javascript:

```js
const Author = graphql(() => {
  const user = query.getFirstUsers;
  return (
    <div>
      <h1>
        {user.id}: {user.username}
      </h1>
      <PagePostsComp user={user} />
    </div>
  );
});

const PagePostsComp = graphql(({ user }) => {
  const args = {
    where: {
      sql: "publish=? and users_id=?",
      val: [String(1), String(user.id)]
    }
  };
  const items = user.posts(args).items;
  return (
    <div>
      {items.map(post =>
        <h2>
          {post.id}: {post.title}
        </h2>
      )}
    </div>
  );
});
```

This is the resulting ajax query:
```json
{
  "query":
    "{ getFirstUsers { id username posts { __typename } } }"
  }
}
```

This is the javascript error:
![image](https://user-images.githubusercontent.com/498409/77235955-16daa500-6bb2-11ea-9f27-cd07dfe00813.png)

Basically, I'm asking:
query.getFirstUsers.posts.items.title

But the Grqphql query only asks:
query.getFirstUsers.posts.__typename

I'm very new to this library so any help is appreciated. Thanks!

**Comment by samdenty** [comment]
@taviroquai can you provide a codesandbox/github issue replicating?

**Comment by taviroquai** [comment]
@samdenty Yes.

You need a PostgreSQL instance for this demo. Just follow few install and run steps.

Demo https://github.com/taviroquai/test-db2graphql-gqless

There is already a generated schema if it helps just looking at the code:
https://github.com/taviroquai/test-db2graphql-gqless/tree/master/src/graphql

Thank you!

**Comment by taviroquai** [comment]
Any news on this? Thanks!

**Comment by Yomanz** [comment]
I'll try and take a look at this soon.

**Comment by taviroquai** [comment]
Hi @Yomanz 

Any news on this?

I'm trying to setup a development enviroment to try to find where is the problem... If you can help me (#129 ) I appreciate very much :)

Thanks!

**Comment by taviroquai** [comment]
@Yomanz Hi, any news on this please? Can I help in any away? Thanks!

**Comment by PabloSzx** [comment]
> Hi, any news on this please? Can I help in any away? Thanks!

There is a rewrite of gqless in progress that should fix this bug and many others, just need a little patience

**Comment by taviroquai** [comment]
@PabloSzx good news! Thank you, of course I can wait. All the best 👍

**Comment by PabloSzx** [comment]
Hi @taviroquai, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 .

This specific issue should be completely fixed, since I have tested in with recursive queries VERY deep and it works fine, thank you
