### ISSUE TITLE
Remove graphql hoc

### ISSUE THREAD

**Issue by elderapo** [gqless/gqless#58]
Let's discuss the removal/improvement of `graphql` HOC. I assume it was created so it's possible to detect a scope of GraphQL schema that is to be queried within a single component - please correct me if I am wrong.

`mobx-react` is using the same approach and it gets pretty messy if a single function component has to be wrapped twice or more:

```ts
import { graphql } from "@gqless/react";
import { observer } from "mobx-react";
import * as React from "react";

export type MyComponentProps = {};

export const MyComponent = graphql(
  observer((props: MyComponentProps) => {
    return <div>content...</div>;
  })
);
```

### Ideas:

1. A basic `Provider`/`Consumer` API would be nice where the user has to just pass `gqless` client into a provider and the rest magically works out of the box. I guess it's "doable" but would require recursive iteration and dynamic wrapping of all react children with `graphql` HOC. This method is expensive and probably should be avoided - just throwing the idea out here.

2. Babel plugin that automatically detects and applies `graphql` HOC to components accessing queries. I think this should work fairly well and doesn't require too much magic/hacking. The downside is that it won't work for people not using babel - obviously :smile: .

3. Last and in my opinion the best solution would be to talk with react team and discuss creating/exposing an API that would allow detecting/hooking into react rendering lifecycles required by libraries like `gqless` & `mobx-react`.

**Comment by joshjg** [comment]
For inspiration: https://github.com/dai-shi/reactive-react-redux

**Comment by samdenty** [comment]
Stated the reason for the HoC in https://github.com/samdenty/gqless/issues/40#issuecomment-558043057 & https://github.com/samdenty/gqless/issues/40#issuecomment-602230102.

> A basic Provider/Consumer API

I don't want to use context for passing gqless data. Works for libraries such as Apollo, cause they're mostly untyped.

> talk with react team and discuss creating/exposing an API

While this would be ideal, I don't think it's the best option. Adding APIs to react directly would make *every component* reactive.

You wouldn't be able to opt-out for a specific Component. Sort of sounds similar to the [deprecated react mixins](https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html)

> Babel plugin that automatically detects and applies graphql HOC to components accessing queries.

This is most likely the route I'll go down. The babel plugin will be necessary for complex apps anyway - so I see it as a progressive enhancement

**Comment by migueloller** [comment]
@samdenty, couldn't we use React context as an "integration" layer between gqless and React while keeping gqless framework agnostic?

I'm not sure I understand how using context for passing data would force it stop being framework agnostic.

**Comment by PabloSzx** [comment]
Hi @elderapo, @joshjg & @migueloller, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 .

About this specific issue, with the new version we released a better alternative of the graphql HOC, but the hoc itself still exists since still has some perks in suspense usage, with 1 less render required than useQuery.
