### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by lukejagodzinski** [gqless/gqless#61]
I see that error handling is mentioned here https://github.com/samdenty/gqless/blob/master/SPEC/TODO.md

How are you planning to implement it? Do you want to export `ErrorBoundary` component from the `@gqless/react` pkg? I guess it's what would be expected with suspense feature, right?

**Comment by PabloSzx** [comment]
The error handling in suspense is now a mess, at least in dev mode, considering the new error dev overlay, so using Error Boundarys is not the perfect solution right now, but possible, but it's important to consider that the new version has a helper hook called `useMetaState` that allows you to do fine-grained error handling, but for sure it could be improved even more.
