### ISSUE TITLE
Updating cache (optimistic update)

### ISSUE THREAD

**Issue by lukejagodzinski** [gqless/gqless#62]
While we're waiting for the official mutations support I'm trying to use the `update` function to perform "optimistic update". What would be the best approach to optimistically remove one element from the list?

Let's say I have a list of users:

```ts
query.users({ teamId }).map(user => <User user={user} />);
```

Now in the `User` component I have the remove button that will perform mutation and I would like to remove user object from the cache without refetching query.

It would be easy if I want to change name.

```ts
update(query.user({ userid }).firstName, "John");
```

But removing values is a mystery :) especially when it's an array. Any clues? :)

**Comment by natew** [comment]
+1 I would call this optimistic updates more clearly too (that was my google originally but didn't find this for some reason)

**Comment by PabloSzx** [comment]
This feature is somewhat implemented with cache manipulation in the new version, feel free to open a new issue after experimenting with it.
