### ISSUE TITLE
Support for LitElement

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [gqless/gqless#65]
Very cool tech! @samdenty Thanks!

Just curious, is gqless React-only? Is it possible to use it with [lit-element](https://lit-element.polymer-project.org/) instead of React?

**Comment by samdenty** [comment]
Although React is currently the only binding, it's framework agnostic.

Using the new `resolved()` function, you can use it with `lit-html`:

https://codesandbox.io/s/little-frog-x9wdl?fontsize=14&hidenavigation=1&module=%2Fsrc%2Findex.tsx&theme=dark

```tsx
  const data = await resolved(
    () =>
      html`
        <ul>
          ${query.hn!.topStories.map(
            story =>
              html`
                <li>${story!.title}</li>
              `
          )}
        </ul>
      `
  )!;

  render(data, document.getElementById("app")!);
```

**Comment by joserochadocarmo** [comment]
Its works! Same in Hyperapp.
[codesandbox hyperapp-v2-jsx](https://codesandbox.io/s/hyperapp-v2-jsx-04qs9?file=/src/index.js)

**Comment by PabloSzx** [comment]
Hi @FluorescentHallucinogen & @joserochadocarmo, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
