### ISSUE TITLE
The refetch and usePoll functions rerender component with old data

### ISSUE THREAD

**Issue by lukejagodzinski** [gqless/gqless#66]
Ok I've checked cache with empty arrays and everything works well there, so no need for changes. However, I found another issue that is not related to the `length = 1` issue. There is a problem in the `refetch` helper. I've confirmed it in my tests. Here is how to reproduce it (sorry for no reproduction repo):

1. Display list of elements, let's say `query.users`. Let's say that initial query returns 5 elements
2. Manually change in DB number of users so that the `query.users` query will return different number of elements now
3. Run refetch for the `query.users` query
4. Component will rerender but will the old list of elements even though that cache was properly updated
5. Run refetch again and now component will render with appropriate number of elements

EDIT:
The same is true for `usePoll`. At first run it gets updated data from gql server, properly updates cache but component is rerendered with the old data. Only the next poll operation updates component properly.

_Originally posted by @lukejagodzinski in https://github.com/samdenty/gqless/issues/63#issuecomment-602674230_

**Comment by PabloSzx** [comment]
With the new version this shouldn't be happening
