### ISSUE TITLE
gqless generate does not work with node ≥ 13.10.0

### ISSUE THREAD

**Issue by Carnewal** [gqless/gqless#67]
It appears that due to an existing issue in the `got` library, the @gqless/cli generate command silently exits when fetching the schema, resulting in nothing being generated.

https://github.com/sindresorhus/got/issues/1107

A workaround is to switch to an earlier version of node.

**Comment by PabloSzx** [comment]
v13.12.0 seems to fix it

![gqless](https://user-images.githubusercontent.com/8672915/77786104-0146fe80-703c-11ea-8ad7-830c4319147a.png)

**Comment by PabloSzx** [comment]
Hi @Carnewal, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
