### ISSUE TITLE
Modifying cache through the query object

### ISSUE THREAD

**Issue by lukejagodzinski** [gqless/gqless#69]
Currently it's possible to modify cache through the query object only when a value was "resolved" in the `graphql` context (sorry for using probably wrong vocabulary). Here is an example:

```ts
const User = graphql(({ user }) => {
  return (
    <div onClick={() => (user.name = String(Math.random()))}>{user.name}</div>
  );
});

const Users = graphql(() => {
  return (
    <div>
      {query.users.map(user => (
        <User key={user.id} user={user} />
      ))}
    </div>
  );
});
```

However, when I try doing something like this it will not work:

```ts
const User = graphql(({ user }) => {
  return <div onClick={() => query.users.pop()}>{user.name}</div>;
});
```

Would it be possible to change that to work more like it's done in MobX. I haven't used MobX before and I'm just finding out how great it is and that a lot of concepts are being used in gqless as well. So if it's possible there then maybe here as well? That would make thinking about cache much easier.

The idea is to just "resolve" values if they are outside of the `graphql` context like in async functions without actually performing the graphql query which of course is not a case already as it's out of the context.

**Comment by PabloSzx** [comment]
Hi @lukejagodzinski, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 

And about this specific issue, cache manipulations are implemented in the new version, and somewhat tested, so you could try them yourself and if you feel like something is not working right, feel free to discuss it / contribute, thank you
