### ISSUE TITLE
Query optimizations

### ISSUE THREAD

**Issue by renanmav** [gqless/gqless#70]
Can we implement something like `relay-compiler` to do query optimizations and remove the runtime overhead?

Here we have a [REPL](https://relay-compiler-repl.netlify.com/) on how relay does these optimizations.

This issue was mainly inspired by https://twitter.com/soney_mathew/status/1242797036522467335

**Comment by PabloSzx** [comment]
I think this is related to static analysis with the gqless compiler project https://github.com/samdenty/gqless#gqless-compiler-wip

**Comment by samdenty** [comment]
Already the Relay REPL, lost the link so thanks for posting it.

gqless already performs query optimizations `InlineFragmentsTransform` / `FlattenTransform` to a degree.

But queries can definitely be further optimized. https://github.com/samdenty/gqless/tree/master/gqless/src/QueryBuilder if anyone's interested

**Comment by PabloSzx** [comment]
Hi @renanmav, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉 

And about this specific issue, in the short term we have to focus in getting the new version stable, but I don't see implementing any compiler-related package in medium term.
