### ISSUE TITLE
Cache persistance

### ISSUE THREAD

**Issue by sfcgeorge** [gqless/gqless#93]
For the slowest bits of our app we like to have the query cache persist between page loads in localstorage (or wherever). We currently use apollo-cache-persist for that. 

We use the fetch method "cache-and-network" meaning that while the app may have stale data on first load at least something is showing, then fresh data loads in the background and updates the UI as necessary.

**Comment by lukejagodzinski** [comment]
I could probably create such a feature if need with a little bit of guidance from @samdenty.

What I was able to determine is that to store cache in the JSON string format you have to:

```ts
localStorage.setItem("cache", JSON.stringify(client.cache.rootValue.toJSON()));
```

Later to convert such a JSON string back into cache you have to:

```ts
client.cache.merge(client.accessor, JSON.parse(localStorage.getItem("cache")!));
```

The only problem with this approach is that no query will be executed if the cache is already there. And so far I don't know how to force query to be executed.

**Comment by lukejagodzinski** [comment]
<!-- prettier-github disable —>

I could probably create such a feature if need with a little bit of guidance from @samdenty.

What I was able to determine is that to store cache in the JSON string format you have to:

```ts
localStorage.setItem("cache", JSON.stringify(client.cache.rootValue.toJSON()));
```

Later to convert such a JSON string back into cache you have to:

```ts
client.cache.merge(client.accessor, JSON.parse(localStorage.getItem("cache")!));
```

The only problem with this approach is that no query will be executed if the cache is already there. And so far I don't know how to force query to be executed.

Also, I'm not sure about cache entries for all the types. If it should be persisted as well or not.

**Comment by sfcgeorge** [comment]
That's nice and simple, thanks. I guess gqless would need to be a callback to hook into every time the cache is updated in order to persist it. But yes it would also need to load from cache and then do the query as well. 

Perhaps this issue should be about adding a fetch policy then. I guess currently if a query result is already in the cache it's never re-fetched? I quite like "cache-and-network" because you get instantly rendered data from the cache, but then it checks to make sure it's up to date. A bit wasteful, but puts my mind at ease. For example in our calendar app clicking prev/next day loads instantly from cache, but then re-fetches the query in case anything has been added.

**Comment by lukejagodzinski** [comment]
From my understanding there is no need to introduce anything like fetch policy from Apollo. The idea behind `gqless` is to have everything working like that automatically. Cache first then network request. Actually I've read somewhere in the docs regarding mutations that you could first perform optimistic mutation of cache and then do an actual mutation (but I guess that's a plan for mutations). You can also force query in the `usePoll` hook even though the cache for query is there. I guess I have to check code how it's being done there and I might update above example.

I think something like that could be done as a plugin as not everyone might want to persist cache. I could help creating something like that if @samdenty gives me some guidance :)

**Comment by PabloSzx** [comment]
About this specific issue, I would say it's completely possible to implement with the new design without too much code, I have been closing all the other issues since they are related to the previous version, but this specific one could be implemented without too much issue, so I will leave it open

**Comment by PabloSzx** [comment]
https://gqless.com/core/persistence 🎉

**Comment by nemonemi** [comment]
I guess this link should be updated to https://gqless.com/client/persistence
