### ISSUE TITLE
Local client state

### ISSUE THREAD

**Issue by sfcgeorge** [gqless/gqless#94]
I love the Apollo feature [local client state](https://www.apollographql.com/docs/react/data/local-state/). I guess you can get part way with Extensions, but what's nice is being able to export local state into queries as variables. So you don't have to manually specify and pass around variables, don't have to endlessly pass variables through props to where you need them. And in combination with cache persist those state variables persist across page loads, and changing a variable anywhere in the app causes queries referencing them to re-fetch.

E.g. we have a calendar app and we use local state for the view (day/month/year) and the date range. Then that state is referenced by both the UI and the queries.

All that said, while I love it the Apollo implementation is crazy buggy and basically untested by them unfortunately. Also since gqless doesn't expose the queries it writes then half of the query syntax features of local state wouldn't apply. I'm not sure what the syntax for using local state as a variable in gqless would be. Finally I can see the argument that state and queries should be managed by separate tools (it's just very convenient having them in one, an all in one model layer). 

Anyway, see this as a pie in the sky tentative feature suggestion that I'd totally understand not doing or wanting to do. Gqless is totally amazing even as it currently stands, I've been wanting something like it for years! Thank you for making and sharing it ❤️

**Comment by PabloSzx** [comment]
Hi @sfcgeorge, We have just released the new version v2 of gqless, please visit https://gqless.com for instructions, it now has Mutation support, Subscriptions support, Normalization and much more, feel free to enter our [discord server](https://discord.gg/2gy8ZQxnGk), to open an issue or a discussion about anything related, thanks you for your contribution! 🎉
